# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56797b1e0482e1ed35ab583a5e31ffeda5e5dc381c0dd5612300f77ed0e7aa079aba41d670efdfe9f1e6618d785b8606f40d67e47d9a0728422f621c0179842a

test:
  secret_key_base: 722c28abd139749a9a1b574760f75872a331705ce3bac92a16fc7c78c310333c58a6e4ff73492937cf4e053af8ca00dd474052978580b9bd6f57af3e197a6abf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
